// Per-screen byte attribution for the js13k bundle, in the spirit of rollup-plugin-visualizer but
// cut along screens rather than modules: here a screen is a set of functions inside `src/index.ts`,
// not its own module, so a module-level treemap cannot answer "what does Attract cost?". Numbers are
// *uncompressed* minified bytes - the Terser output the real build hands to Roadroller - because
// Roadroller and zip savings belong to the bundle as a whole and cannot be split per screen.
// `scripts/check-size.mjs` stays the authority on the shipped size.
//
// How it works:
//   1. Re-run the package's own Vite config (same defines and aliases, js13k plugins dropped)
//      unminified with a sourcemap, then Terser it with that config's own `terserOptions`.
//   2. Walk the resulting sourcemap and charge every generated byte to an original source line.
//   3. Parse the sources with TypeScript, fold lines into top-level declarations, and link each
//      declaration to the declarations it references, following imports across modules.
//   4. Flood that reference graph from each screen's roots. A declaration reached from exactly one
//      screen is that screen's own cost; reached from several it is shared; reached from none it is
//      engine/shell code that runs whatever is on screen.
//
// Roots come from a `screenReport` field in the package's own package.json (the same opt-in shape
// `sizeBudget` uses); without one, only the module-level table is printed.
//
// Usage: node scripts/screen-report.mjs [--json] [--detail]
import { mkdtempSync, readFileSync, readdirSync, rmSync } from "node:fs";
import { createRequire } from "node:module";
import { tmpdir } from "node:os";
import { dirname, relative, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { resolveEntry } from "./entry.mjs";

const argv = process.argv.slice(2);
const option = (name) => {
  const at = argv.indexOf(name);
  return at < 0 ? undefined : argv[at + 1];
};

const asJson = argv.includes("--json");
const withDetail = argv.includes("--detail");
const entry = resolveEntry();

const norm = (path) => path.replaceAll("\\", "/");
const pkgDir = norm(entry.dir).replace(/\/$/, "");
const rel = (path) => norm(relative(pkgDir, path));
const pkg = JSON.parse(readFileSync(`${pkgDir}/package.json`, "utf8"));
// Report on whatever the project actually ships — derived from the `build` script's own `--mode`.
const mode = option("--mode") ?? /--mode\s+(\S+)/.exec(pkg.scripts?.build ?? "")?.[1] ?? "release";

// pnpm keeps each package's devDependencies under its own store path, so a root-level script cannot
// import vite/typescript/terser by bare specifier - resolve them against the package instead.
const req = createRequire(`${pkgDir}/package.json`);
const ts = req("typescript");
const { minify } = req("terser");
const { build, loadConfigFromFile } = await import(pathToFileURL(req.resolve("vite")).href);

// ---------------------------------------------------------------- build + minify

async function minifiedBundle() {
  const outDir = mkdtempSync(`${norm(tmpdir())}/screen-report-`);
  try {
    const loaded = await loadConfigFromFile({ command: "build", mode }, `${pkgDir}/vite.config.ts`, pkgDir, "silent");
    const base = loaded?.config ?? {};
    await build({
      ...base,
      configFile: false,
      root: pkgDir,
      // Roadroller, ECT and advzip all run past the point where a sourcemap still exists, and only
      // slow this down. Vite's own internal plugins are untouched by an empty user plugin list.
      plugins: [],
      logLevel: "silent",
      build: { ...base.build, outDir, emptyOutDir: true, sourcemap: true, minify: false },
    });

    const chunk = readdirSync(outDir).find((file) => file.endsWith(".js"));
    if (!chunk) throw new Error(`${entry.name}: the report build produced no JS chunk`);
    const result = await minify(readFileSync(`${outDir}/${chunk}`, "utf8"), {
      ...(base.build?.terserOptions ?? {}),
      sourceMap: { content: JSON.parse(readFileSync(`${outDir}/${chunk}.map`, "utf8")) },
    });
    return { code: result.code, map: JSON.parse(result.map) };
  } finally {
    rmSync(outDir, { recursive: true, force: true });
  }
}

// ---------------------------------------------------------------- sourcemap -> bytes per line

const B64 = new Int8Array(128).fill(-1);
for (const [index, char] of [..."ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"].entries())
  B64[char.charCodeAt(0)] = index;

/** Decodes `mappings` into one array of `[genCol, sourceIndex, sourceLine, sourceCol]` per generated line. */
function decodeMappings(mappings) {
  const lines = [];
  let source = 0;
  let line = 0;
  let column = 0;
  for (const group of mappings.split(";")) {
    const segments = [];
    let generated = 0;
    if (group)
      for (const text of group.split(",")) {
        let at = 0;
        const read = () => {
          let shift = 0;
          let value = 0;
          let more;
          do {
            const digit = B64[text.charCodeAt(at++)];
            more = digit & 32;
            value += (digit & 31) << shift;
            shift += 5;
          } while (more);
          return value & 1 ? -(value >>> 1) : value >>> 1;
        };
        generated += read();
        if (at < text.length) {
          source += read();
          line += read();
          column += read();
          segments.push([generated, source, line, column]);
        } else {
          segments.push([generated, -1, 0, 0]);
        }
      }
    lines.push(segments);
  }
  return lines;
}

/**
 * Charges every byte of the generated file to the original line its nearest preceding mapping points
 * at - the span split source-map-explorer uses. Returns bytes keyed `"<file>:<line>"` plus whatever
 * no mapping claimed (Terser scaffolding, inlined helpers, folded constants).
 */
function bytesByOriginalLine(code, map) {
  const decoded = decodeMappings(map.mappings);
  const sources = map.sources.map(norm);
  const generated = code.split("\n");
  const bytes = new Map();
  let unmapped = 0;

  for (const [index, text] of generated.entries()) {
    const newline = index < generated.length - 1 ? 1 : 0;
    const segments = decoded[index] ?? [];
    if (!segments.length) {
      unmapped += Buffer.byteLength(text) + newline;
      continue;
    }
    unmapped += Buffer.byteLength(text.slice(0, segments[0][0]));
    for (const [at, segment] of segments.entries()) {
      const end = at + 1 < segments.length ? segments[at + 1][0] : text.length;
      const size = Buffer.byteLength(text.slice(segment[0], end)) + (at === segments.length - 1 ? newline : 0);
      if (segment[1] < 0 || !sources[segment[1]]) unmapped += size;
      else {
        const key = `${sources[segment[1]]}:${segment[2]}`;
        bytes.set(key, (bytes.get(key) ?? 0) + size);
      }
    }
  }
  return { bytes, unmapped };
}

// ---------------------------------------------------------------- TypeScript symbol graph

const NAMING_PARENTS = new Set([
  ts.SyntaxKind.ImportSpecifier,
  ts.SyntaxKind.ImportClause,
  ts.SyntaxKind.NamespaceImport,
  ts.SyntaxKind.TypeReference,
  ts.SyntaxKind.QualifiedName,
  ts.SyntaxKind.PropertySignature,
  ts.SyntaxKind.MethodSignature,
]);

/** True for identifiers that name something rather than reference it (`const foo`, `{ foo: 1 }`, `a.foo`). */
function namesRatherThanReferences(node) {
  const parent = node.parent;
  if (!parent) return false;
  if (NAMING_PARENTS.has(parent.kind)) return true;
  if (ts.isPropertyAccessExpression(parent)) return parent.name === node;
  if (ts.isPropertyAssignment(parent)) return parent.name === node;
  // `{ foo }` in an object literal both names and reads `foo`.
  if (ts.isShorthandPropertyAssignment(parent)) return false;
  return "name" in parent && parent.name === node;
}

function collectRefs(node, into) {
  if (ts.isIdentifier(node)) {
    if (!namesRatherThanReferences(node)) into.add(node.text);
    return;
  }
  if (ts.isTypeNode(node) && !ts.isTypeQueryNode(node)) return;
  ts.forEachChild(node, (child) => collectRefs(child, into));
}

function bindingNames(name, into) {
  if (ts.isIdentifier(name)) into.push(name.text);
  else for (const element of name.elements) if (!ts.isOmittedExpression(element)) bindingNames(element.name, into);
}

/** Resolves a relative import specifier to a parsed source file, or undefined when it leaves the tree. */
function resolveImport(fromFile, specifier, known) {
  if (!specifier.startsWith(".")) return undefined;
  const base = norm(resolve(dirname(fromFile), specifier));
  return [base, `${base}.ts`, `${base}/index.ts`].find((candidate) => known.has(candidate));
}

/**
 * Parses each source into top-level declarations with their line ranges, then links every declaration
 * to the declarations it references. Local shadowing is not modelled - a parameter that happens to
 * share a top-level name adds a spurious edge, which can only push a symbol towards "shared".
 */
function buildGraph(files) {
  const known = new Set(files);
  const decls = new Map();
  const perFile = new Map();

  for (const file of files) {
    const source = ts.createSourceFile(
      file,
      readFileSync(file, "utf8"),
      ts.ScriptTarget.Latest,
      true,
      ts.ScriptKind.TS,
    );
    const lineOwner = [];
    const byName = new Map();
    const imports = new Map();
    const claimed = [];

    const claim = (name, spanNode, refsNode) => {
      const key = `${rel(file)}#${name}`;
      byName.set(name, key);
      claimed.push({
        key,
        refsNode: refsNode ?? spanNode,
        start: source.getLineAndCharacterOfPosition(spanNode.getStart(source)).line,
        end: source.getLineAndCharacterOfPosition(spanNode.getEnd()).line,
      });
      decls.set(key, { key, file, name, refs: new Set(), bytes: 0 });
    };

    for (const statement of source.statements) {
      if (ts.isImportDeclaration(statement)) {
        const target = resolveImport(file, statement.moduleSpecifier.text, known);
        const clause = statement.importClause;
        if (!target || !clause || clause.isTypeOnly) continue;
        if (clause.name) imports.set(clause.name.text, { file: target, name: "default" });
        const bindings = clause.namedBindings;
        if (bindings && ts.isNamedImports(bindings))
          for (const element of bindings.elements)
            if (!element.isTypeOnly)
              imports.set(element.name.text, { file: target, name: (element.propertyName ?? element.name).text });
        continue;
      }
      if (ts.isFunctionDeclaration(statement) || ts.isClassDeclaration(statement)) {
        if (statement.name) claim(statement.name.text, statement);
        continue;
      }
      if (ts.isVariableStatement(statement)) {
        const [first] = statement.declarationList.declarations;
        for (const declaration of statement.declarationList.declarations) {
          const names = [];
          bindingNames(declaration.name, names);
          // A destructured declarator has no single owning name, so every binding it introduces
          // shares its bytes and its references.
          for (const name of names) claim(name, declaration === first ? statement : declaration, declaration);
        }
        continue;
      }
      if (ts.isInterfaceDeclaration(statement) || ts.isTypeAliasDeclaration(statement)) continue;
      // Bare top-level statements (`initLines(...)`, `runLoop(...)`) are module start-up, not symbols.
      claim(`<init:${source.getLineAndCharacterOfPosition(statement.getStart(source)).line + 1}>`, statement);
    }

    for (const { key, refsNode, start, end } of claimed) {
      collectRefs(refsNode, decls.get(key).refs);
      for (let line = start; line <= end; line++) if (lineOwner[line] === undefined) lineOwner[line] = key;
    }
    perFile.set(file, { lineOwner, byName, imports });
  }

  // Second pass: identifier text -> declaration key, own file first, then imports.
  for (const { byName, imports } of perFile.values())
    for (const key of byName.values()) {
      const decl = decls.get(key);
      const resolved = new Set();
      for (const name of decl.refs) {
        const local = byName.get(name);
        if (local) {
          if (local !== key) resolved.add(local);
          continue;
        }
        const imported = imports.get(name);
        const target = imported && perFile.get(imported.file)?.byName.get(imported.name);
        if (target && target !== key) resolved.add(target);
      }
      decl.refs = resolved;
    }

  return { decls, perFile };
}

// ---------------------------------------------------------------- ownership

function rootKey(root, decls) {
  if (root.includes("#")) {
    if (!decls.has(root)) throw new Error(`screenReport: no declaration "${root}"`);
    return root;
  }
  const matches = [...decls.keys()].filter((key) => key.endsWith(`#${root}`));
  if (!matches.length) throw new Error(`screenReport: no declaration named "${root}"`);
  if (matches.length > 1) throw new Error(`screenReport: "${root}" is ambiguous - use one of ${matches.join(", ")}`);
  return matches[0];
}

function reach(roots, decls) {
  const seen = new Set();
  const stack = [...roots];
  while (stack.length) {
    const key = stack.pop();
    if (seen.has(key)) continue;
    seen.add(key);
    for (const next of decls.get(key)?.refs ?? []) stack.push(next);
  }
  return seen;
}

// ---------------------------------------------------------------- run

const bundle = await minifiedBundle();
const total = Buffer.byteLength(bundle.code);
const { bytes: lineBytes, unmapped } = bytesByOriginalLine(bundle.code, bundle.map);

const sourceFiles = [...new Set(bundle.map.sources.map(norm))].filter(
  (file) => file.startsWith(`${pkgDir}/`) && file.endsWith(".ts"),
);
const { decls, perFile } = buildGraph(sourceFiles);

// Fold per-line bytes into declarations. Lines outside any declaration (imports, blank lines, files
// that never got parsed) are module framing and count towards the shell.
const moduleBytes = new Map();
let framing = 0;
for (const [key, size] of lineBytes) {
  const at = key.lastIndexOf(":");
  const file = key.slice(0, at);
  moduleBytes.set(rel(file), (moduleBytes.get(rel(file)) ?? 0) + size);
  const owner = perFile.get(file)?.lineOwner[Number(key.slice(at + 1))];
  if (owner) decls.get(owner).bytes += size;
  else framing += size;
}

const config = pkg.screenReport;
const owners = new Map();
for (const [screen, roots] of Object.entries(config?.screens ?? {}))
  for (const key of reach(
    roots.map((root) => rootKey(root, decls)),
    decls,
  )) {
    if (!owners.has(key)) owners.set(key, new Set());
    owners.get(key).add(screen);
  }

const SHELL = "engine / shell";
const screenCount = Object.keys(config?.screens ?? {}).length;
const buckets = new Map();
const put = (label, kind, decl) => {
  if (!buckets.has(label)) buckets.set(label, { label, kind, bytes: 0, symbols: [] });
  const bucket = buckets.get(label);
  bucket.bytes += decl.bytes;
  bucket.symbols.push(decl);
};
for (const decl of decls.values()) {
  if (!decl.bytes) continue;
  const owned = [...(owners.get(decl.key) ?? [])].sort();
  if (!owned.length) put(SHELL, "shell", decl);
  else if (owned.length === 1) put(owned[0], "screen", decl);
  else put(`shared: ${owned.length === screenCount ? "every screen" : owned.join(" + ")}`, "shared", decl);
}
if (framing) put(SHELL, "shell", { key: "<module framing>", bytes: framing });

// Screen combinations below this are real but too small to be worth a row of their own.
const MINOR = total * 0.002;
const minor = [...buckets.values()].filter((row) => row.kind === "shared" && row.bytes < MINOR);
if (minor.length > 1) {
  for (const row of minor) buckets.delete(row.label);
  buckets.set("shared: smaller combinations", {
    label: `shared: ${minor.length} smaller combinations`,
    kind: "shared",
    bytes: minor.reduce((bytes, row) => bytes + row.bytes, 0),
    symbols: minor.flatMap((row) => row.symbols),
  });
}

const rank = { screen: 0, shared: 1, shell: 2 };
const rows = [...buckets.values()].sort((a, b) => rank[a.kind] - rank[b.kind] || b.bytes - a.bytes);
const modules = [...moduleBytes].sort((a, b) => b[1] - a[1]);

if (asJson) {
  console.log(
    JSON.stringify(
      {
        package: entry.name,
        totalBytes: total,
        unmappedBytes: unmapped,
        buckets: rows.map(({ label, kind, bytes, symbols }) => ({
          label,
          kind,
          bytes,
          symbols: symbols
            .filter((symbol) => symbol.bytes)
            .sort((a, b) => b.bytes - a.bytes)
            .map((symbol) => ({ symbol: symbol.key, bytes: symbol.bytes })),
        })),
        modules: modules.map(([file, bytes]) => ({ file, bytes })),
      },
      null,
      2,
    ),
  );
  process.exit(0);
}

// A dependency pulled out of the store can carry an absurdly long path; keep the table readable.
const MAX_LABEL = 52;
const short = (label) => (label.length <= MAX_LABEL ? label : `...${label.slice(3 - MAX_LABEL)}`);
const width = Math.max(
  24,
  ...rows.map((row) => short(row.label).length),
  ...modules.map(([file]) => short(file).length),
);
const pad = (value, size) => String(value).padStart(size);
const percent = (bytes) => pad(`${((bytes / total) * 100).toFixed(1)}%`, 6);
const bar = (bytes) => "#".repeat(Math.round((bytes / total) * 30)).padEnd(30, ".");
const rule = `  ${"-".repeat(width + 47)}`;
const line = (label, bytes) =>
  console.log(`  ${short(label).padEnd(width)} ${pad(bytes, 7)} ${percent(bytes)}  ${bar(bytes)}`);

console.log(
  `\n  ${entry.name} (--mode ${mode}) - uncompressed minified bundle: ${total} bytes (before Roadroller and zip)`,
);
console.log(`\n  ${"where".padEnd(width)} ${pad("bytes", 7)} ${pad("share", 6)}`);
console.log(rule);
let previous;
for (const row of rows) {
  if (previous && previous !== row.kind) console.log();
  previous = row.kind;
  line(row.label, row.bytes);
}
if (unmapped) {
  console.log();
  console.log(
    `  ${"unattributed".padEnd(width)} ${pad(unmapped, 7)} ${percent(unmapped)}  folded constants, Terser scaffolding`,
  );
}

if (!config) {
  console.log('\n  package.json declares no "screenReport" - screens not split.');
} else {
  const sum = (kind) => rows.filter((row) => row.kind === kind).reduce((bytes, row) => bytes + row.bytes, 0);
  const exclusive = sum("screen");
  const shared = sum("shared");
  console.log(
    `\n  screen-exclusive ${exclusive} B | shared between screens ${shared} B | ` +
      `screen-independent ${total - exclusive - shared - unmapped} B`,
  );
}

console.log(`\n  by module\n${rule}`);
for (const [file, bytes] of modules) line(file, bytes);

if (withDetail)
  for (const row of rows) {
    const top = row.symbols.filter((symbol) => symbol.bytes).sort((a, b) => b.bytes - a.bytes);
    if (!top.length) continue;
    console.log(`\n  ${row.label} (${row.bytes} B)\n${rule}`);
    for (const symbol of top.slice(0, 20)) console.log(`  ${pad(symbol.bytes, 7)}  ${symbol.key}`);
    if (top.length > 20) console.log(`  ${pad("", 7)}  ... and ${top.length - 20} more`);
  }

console.log();
